server:
  port: 8001

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource # Druid数据源（阿里巴巴提供）
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySql 8.0 驱动包
      url: jdbc:mysql://47.100.250.100:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false&SslMode=Required
      username: yixiaobai
      password: Pa$$w0rd
      # 配置监控界面统计拦截的filter，去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,log4j,config
      # 最大链接数
      max-active: 100
      # 初始化大小
      initial-size: 1
      # 获取链接等待超时时间
      max-wait: 60000
      # 最小链接数
      min-idle: 1
      # 间隔多久才进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
logging:
  level:
    root: debug

# MyBatis分页助手配置
# 需要导入自己的mango-core jar包
# pageHelper
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  # 支持方法参数
#  support-methods-arguments: true
#  params: count=countSql